### ISSUE TITLE
Won't work in Fastify v5

### ISSUE THREAD

**Issue by ben-hn** [fastify/fastify-diagnostics-channel#80]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

4.28.1

### Stopped working in version

5.0.0

### Node.js version

20.17.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

rolling

### 💥 Regression Report

Just needs the compatible fastify version bumping to 5, and then releasing an update to NPM.

### Steps to Reproduce

Install fastify 5, try and use this plugin

### Expected Behavior

It shouldn't complain about not finding fastify v4

**Comment by mcollina** [comment]
This plugin does not make much sense in fastify v5. This feature is now built in: https://fastify.dev/docs/latest/Reference/Hooks/#diagnostics-channel-hooks.

**Comment by ben-hn** [comment]
Ah perfect!

Might be worth chucking up a massive DEPRECATED banner on the README and linking to that page instead!

Thanks!

**Comment by mcollina** [comment]
@ben-hn would you like to send a PR?

**Comment by Eomm** [comment]
Released a new major with the deprecation warning: 
<img width="1205" alt="image" src="https://github.com/user-attachments/assets/226b5aa3-ec24-4e96-80a9-f04528dcf369">


Feel free to add it to the readme

**Comment by Eomm** [comment]
As follow-up - I would archive this repo since it does not work with fastify v5 and it has been deprecated already

Any objection @fastify/plugins ?

**Comment by Fdawgs** [comment]
No objection here.
